PX-907 / Simplify Phone Input
perxhealth/react-ui pull request #39
Opened 2023-08-29 02:45 UTC by jmhar3

## What is the desired outcome?
Modify the PhoneInput to allow for simpler options.

## Why do we want this?
Patrick wants a phone input with the prefix + suffix removed.

## How?
Make prefix + suffix optional.

## Testing?
Open storybook to try it for yourself

## Screenshots
N/A (see below)

## Anything else? Questions? Concerns?
I'm getting an error when attempting to run storybook so I haven't been able to preview locally.

2023-09-01 07:16 UTC, lukerollans requested changes, later dismissed
@jmhar3 I think there's just a small handful of things to take care of here

## Checklist
1. Absorb `showPrefix` and `showSuffix` in to a `format: "international" | "local"` prop
2. When in `"international"` mode, report back the number inclusive of international code
3. When in `"local"` mode, report back whatever the user enters while still restricting input to numbers only.
4. Fix Chakra UI storybook styling. Either upgrade to fix the Chakra UI Storybook addon, or add ChakraProvider to each story inline

## Implementation
I think I'm starting to remember why we opted not to use `libphonenumber-js` - we only allow AU or US numbers, so a global validation library addition to the bundle wasn't justifiable.

Given we already have `maxLength` set, hopefully this won't be too much effort

2023-09-05 04:18 UTC, sumac13 commented on src/components/forms/PhoneInput.tsx
> +import parsePhoneNumber from "libphonenumber-js"
I think the linter here wants you to use 
```suggestion
import { parsePhoneNumber } from "libphonenumber-js"
```

2023-09-05 04:25 UTC, sumac13 requested changes

2023-09-05 04:25 UTC, sumac13 commented on src/components/forms/PhoneInput.tsx
> +            parsePhoneNumber(phoneNumber, currentCountry.countryCode).isValid()
couple of lint issues that are worth looking at too

2023-09-05 04:25 UTC, sumac13 commented on stories/components/forms/PhoneInput.stories.tsx
> +  showPrefix: false,
should these `show...` flags be removed if we are moving to the Format param instead?

2023-09-05 04:25 UTC, sumac13 commented on src/components/forms/PhoneInput.tsx
> +        const phoneNumber = `${
I think there is a method in the `libphonenumber-js` lib that will output this for you without needing to do string templating like this and ensures it handles all edge cases.

Something like 
```
const phoneNumber = isInternational ? parsePhoneNumber(value, currentCountry.countryCode).number : value
```

2023-09-06 03:09 UTC, sumac13 approved these changes

2023-09-06 05:08 UTC, merged